import os

# --- 1. GLOBAL SETTINGS ---
RANDOM_SEED = 42
DEBUG_MODE = True

# --- 2. PATHS ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODEL_DIR = os.path.join(BASE_DIR, "..", "models")
DATA_DIR = os.path.join(BASE_DIR, "..", "data")

# --- 3. MODEL PERFORMANCE THRESHOLDS ---
CI_ACCURACY_THRESHOLD = 0.80

# --- 4. ATTACK CONFIGURATIONS ---
EPS_VALUES = [0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5]
HSJ_MAX_ITER = 50
HSJ_MAX_EVAL = 100
HSJ_INIT_EVAL = 10
FGM_EPS = 0.2

# --- 5. TRAINING CONFIGURATIONS ---
SURROGATE_LR = 0.001
SURROGATE_EPOCHS = 100
EARLY_STOPPING_PATIENCE = 5
TRAIN_VAL_SPLIT = 0.2

# --- 6. ENSEMBLE DEFENSE SETTINGS ---
CONFIDENCE_THRESHOLD = 0.15
